# Required metadata
sonar.projectKey=devops-assignment-api
sonar.projectName=DevOps Assignment API
sonar.projectVersion=1.0

# Path to source directories (required)
sonar.sources=.
sonar.exclusions=node_modules/**, test/**, coverage/**

# Path to test directories
sonar.tests=test/

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info
